2018-11-27 21:41:02.142 +07:00 [ERR] Ошибка при отправке даных: Обмен не найденн: TcpIp_table_NONE1

2018-11-27 21:41:09.573 +07:00 [ERR] Ошибка при отправке даных: Обмен не найденн: TcpIp_table_NONE1

2018-11-27 21:45:50.976 +07:00 [ERR] Ошибка при отправке даных: Обмен не найденн: TcpIp_table_461
Обмен не найденн: TcpIp_table_591

2018-11-27 21:47:35.496 +07:00 [ERR] Ошибка при отправке даных: Обмен не найденн: TcpIp_table_461

2018-11-27 21:47:46.616 +07:00 [ERR] Ошибка при отправке даных: Обмен не найденн: TcpIp_table_461

2018-11-27 21:47:57.760 +07:00 [ERR] Ошибка при отправке даных: Обмен не найденн: TcpIp_table_461

2018-11-27 21:58:06.314 +07:00 [ERR] KafkaException= Local: Message timed out для Vidor1
Confluent.Kafka.KafkaException: Local: Message timed out
   at Infrastructure.MessageBroker.Produser.KafkaProducer.<ProduceAsync>d__4.MoveNext() in D:\Git\CommunicationWebService\src\Infrastructure.MessageBroker1\Produser\KafkaProducer.cs:line 94
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at DeviceForExchange.Device`1.<Send2Produder>d__21.MoveNext() in D:\Git\CommunicationWebService\src\Device.Base\Device.cs:line 197
2018-11-27 21:58:06.354 +07:00 [ERR] Ошибка при отправке даных: Обмен не найденн: TcpIp_table_461
Обмен не найденн: TcpIp_table_591

2018-11-27 21:58:20.695 +07:00 [ERR] Ошибка инициализации соединения: "Попытка установить соединение была безуспешной, т.к. от другого компьютера за требуемое время не получен нужный отклик, или было разорвано уже установленное соединение из-за неверного отклика уже подключенного компьютера 10.27.15.199:4001"
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (0x80004005): Попытка установить соединение была безуспешной, т.к. от другого компьютера за требуемое время не получен нужный отклик, или было разорвано уже установленное соединение из-за неверного отклика уже подключенного компьютера 10.27.15.199:4001
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpClient.<>c.<ConnectAsync>b__27_1(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Transport.TcpIp.Concrete.TcpIpTransport.<ReOpen>d__39.MoveNext() in D:\Git\CommunicationWebService\src\Communication.TcpIp\Concrete\TcpIpTransport.cs:line 142
2018-11-27 21:58:28.319 +07:00 [ERR] KafkaException= Local: Message timed out для Vidor1
Confluent.Kafka.KafkaException: Local: Message timed out
   at Infrastructure.MessageBroker.Produser.KafkaProducer.<ProduceAsync>d__4.MoveNext() in D:\Git\CommunicationWebService\src\Infrastructure.MessageBroker1\Produser\KafkaProducer.cs:line 94
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at DeviceForExchange.Device`1.<Send2Produder>d__21.MoveNext() in D:\Git\CommunicationWebService\src\Device.Base\Device.cs:line 197
2018-11-27 21:58:28.330 +07:00 [ERR] Ошибка при отправке даных: Обмен не найденн: TcpIp_table_461
Обмен не найденн: TcpIp_table_591

2018-11-27 21:58:44.751 +07:00 [ERR] Ошибка инициализации соединения: "Попытка установить соединение была безуспешной, т.к. от другого компьютера за требуемое время не получен нужный отклик, или было разорвано уже установленное соединение из-за неверного отклика уже подключенного компьютера 10.27.15.199:4001"
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (0x80004005): Попытка установить соединение была безуспешной, т.к. от другого компьютера за требуемое время не получен нужный отклик, или было разорвано уже установленное соединение из-за неверного отклика уже подключенного компьютера 10.27.15.199:4001
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpClient.<>c.<ConnectAsync>b__27_1(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Transport.TcpIp.Concrete.TcpIpTransport.<ReOpen>d__39.MoveNext() in D:\Git\CommunicationWebService\src\Communication.TcpIp\Concrete\TcpIpTransport.cs:line 142
2018-11-27 21:58:49.329 +07:00 [ERR] KafkaException= Local: Message timed out для Vidor1
Confluent.Kafka.KafkaException: Local: Message timed out
   at Infrastructure.MessageBroker.Produser.KafkaProducer.<ProduceAsync>d__4.MoveNext() in D:\Git\CommunicationWebService\src\Infrastructure.MessageBroker1\Produser\KafkaProducer.cs:line 94
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at DeviceForExchange.Device`1.<Send2Produder>d__21.MoveNext() in D:\Git\CommunicationWebService\src\Device.Base\Device.cs:line 197
2018-11-27 21:58:49.340 +07:00 [ERR] Ошибка при отправке даных: Обмен не найденн: TcpIp_table_461
Обмен не найденн: TcpIp_table_591

2018-11-27 21:59:08.792 +07:00 [ERR] Ошибка инициализации соединения: "Попытка установить соединение была безуспешной, т.к. от другого компьютера за требуемое время не получен нужный отклик, или было разорвано уже установленное соединение из-за неверного отклика уже подключенного компьютера 10.27.15.199:4001"
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (0x80004005): Попытка установить соединение была безуспешной, т.к. от другого компьютера за требуемое время не получен нужный отклик, или было разорвано уже установленное соединение из-за неверного отклика уже подключенного компьютера 10.27.15.199:4001
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpClient.<>c.<ConnectAsync>b__27_1(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Transport.TcpIp.Concrete.TcpIpTransport.<ReOpen>d__39.MoveNext() in D:\Git\CommunicationWebService\src\Communication.TcpIp\Concrete\TcpIpTransport.cs:line 142
2018-11-27 21:59:40.285 +07:00 [ERR] Ошибка при отправке даных: Обмен не найденн: TcpIp_table_461
Обмен не найденн: TcpIp_table_591

2018-11-27 22:05:38.444 +07:00 [ERR] KafkaException= Local: Message timed out для Vidor1
Confluent.Kafka.KafkaException: Local: Message timed out
   at Infrastructure.MessageBroker.Produser.KafkaProducer.<ProduceAsync>d__4.MoveNext() in D:\Git\CommunicationWebService\src\Infrastructure.MessageBroker1\Produser\KafkaProducer.cs:line 94
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at DeviceForExchange.Device`1.<Send2Produder>d__21.MoveNext() in D:\Git\CommunicationWebService\src\Device.Base\Device.cs:line 197
2018-11-27 22:05:38.489 +07:00 [ERR] Ошибка при отправке даных: Обмен не найденн: TcpIp_table_461
Обмен не найденн: TcpIp_table_591

2018-11-27 22:05:52.851 +07:00 [ERR] Ошибка инициализации соединения: "Попытка установить соединение была безуспешной, т.к. от другого компьютера за требуемое время не получен нужный отклик, или было разорвано уже установленное соединение из-за неверного отклика уже подключенного компьютера 10.27.15.199:4001"
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (0x80004005): Попытка установить соединение была безуспешной, т.к. от другого компьютера за требуемое время не получен нужный отклик, или было разорвано уже установленное соединение из-за неверного отклика уже подключенного компьютера 10.27.15.199:4001
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpClient.<>c.<ConnectAsync>b__27_1(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Transport.TcpIp.Concrete.TcpIpTransport.<ReOpen>d__39.MoveNext() in D:\Git\CommunicationWebService\src\Communication.TcpIp\Concrete\TcpIpTransport.cs:line 142
2018-11-27 22:06:00.153 +07:00 [ERR] Ошибка при отправке даных: Обмен не найденн: TcpIp_table_461
Обмен не найденн: TcpIp_table_591

