2018-11-26 11:58:37.735 +07:00 [ERR] Ошибка инициализации соединения: "Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение 192.168.100.3:50000"
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (0x80004005): Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение 192.168.100.3:50000
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpClient.<>c.<ConnectAsync>b__27_1(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Transport.TcpIp.Concrete.TcpIpTransport.<ReOpen>d__39.MoveNext() in D:\Git\CommunicationWebService\src\Communication.TcpIp\Concrete\TcpIpTransport.cs:line 141
2018-11-26 11:58:41.824 +07:00 [ERR] Ошибка инициализации соединения: "Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение 192.168.100.3:50000"
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (0x80004005): Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение 192.168.100.3:50000
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpClient.<>c.<ConnectAsync>b__27_1(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Transport.TcpIp.Concrete.TcpIpTransport.<ReOpen>d__39.MoveNext() in D:\Git\CommunicationWebService\src\Communication.TcpIp\Concrete\TcpIpTransport.cs:line 141
2018-11-26 11:58:45.870 +07:00 [ERR] Ошибка инициализации соединения: "Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение 192.168.100.3:50000"
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (0x80004005): Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение 192.168.100.3:50000
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpClient.<>c.<ConnectAsync>b__27_1(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Transport.TcpIp.Concrete.TcpIpTransport.<ReOpen>d__39.MoveNext() in D:\Git\CommunicationWebService\src\Communication.TcpIp\Concrete\TcpIpTransport.cs:line 141
2018-11-26 12:43:15.724 +07:00 [ERR] Ошибка инициализации соединения: "Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение 192.168.100.3:50000"
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (0x80004005): Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение 192.168.100.3:50000
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpClient.<>c.<ConnectAsync>b__27_1(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Transport.TcpIp.Concrete.TcpIpTransport.<ReOpen>d__39.MoveNext() in D:\Git\CommunicationWebService\src\Communication.TcpIp\Concrete\TcpIpTransport.cs:line 141
2018-11-26 12:43:59.549 +07:00 [ERR] Ошибка инициализации соединения: "Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение 192.168.100.3:50000"
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (0x80004005): Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение 192.168.100.3:50000
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpClient.<>c.<ConnectAsync>b__27_1(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Transport.TcpIp.Concrete.TcpIpTransport.<ReOpen>d__39.MoveNext() in D:\Git\CommunicationWebService\src\Communication.TcpIp\Concrete\TcpIpTransport.cs:line 141
2018-11-26 12:44:03.611 +07:00 [ERR] Ошибка инициализации соединения: "Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение 192.168.100.3:50000"
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (0x80004005): Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение 192.168.100.3:50000
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpClient.<>c.<ConnectAsync>b__27_1(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Transport.TcpIp.Concrete.TcpIpTransport.<ReOpen>d__39.MoveNext() in D:\Git\CommunicationWebService\src\Communication.TcpIp\Concrete\TcpIpTransport.cs:line 141
2018-11-26 12:44:41.231 +07:00 [ERR] Ошибка инициализации соединения: "Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение 192.168.100.3:50000"
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (0x80004005): Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение 192.168.100.3:50000
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpClient.<>c.<ConnectAsync>b__27_1(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Transport.TcpIp.Concrete.TcpIpTransport.<ReOpen>d__39.MoveNext() in D:\Git\CommunicationWebService\src\Communication.TcpIp\Concrete\TcpIpTransport.cs:line 141
2018-11-26 12:45:20.017 +07:00 [ERR] Ошибка инициализации соединения: "Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение 192.168.100.3:50000"
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (0x80004005): Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение 192.168.100.3:50000
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpClient.<>c.<ConnectAsync>b__27_1(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Transport.TcpIp.Concrete.TcpIpTransport.<ReOpen>d__39.MoveNext() in D:\Git\CommunicationWebService\src\Communication.TcpIp\Concrete\TcpIpTransport.cs:line 141
2018-11-26 12:45:24.091 +07:00 [ERR] Ошибка инициализации соединения: "Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение 192.168.100.3:50000"
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (0x80004005): Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение 192.168.100.3:50000
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpClient.<>c.<ConnectAsync>b__27_1(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Transport.TcpIp.Concrete.TcpIpTransport.<ReOpen>d__39.MoveNext() in D:\Git\CommunicationWebService\src\Communication.TcpIp\Concrete\TcpIpTransport.cs:line 141
2018-11-26 12:46:03.990 +07:00 [ERR] Ошибка инициализации соединения: "Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение 192.168.100.3:50000"
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (0x80004005): Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение 192.168.100.3:50000
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpClient.<>c.<ConnectAsync>b__27_1(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Transport.TcpIp.Concrete.TcpIpTransport.<ReOpen>d__39.MoveNext() in D:\Git\CommunicationWebService\src\Communication.TcpIp\Concrete\TcpIpTransport.cs:line 141
2018-11-26 12:48:28.109 +07:00 [ERR] Ошибка инициализации соединения: "Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение 192.168.100.3:50000"
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (0x80004005): Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение 192.168.100.3:50000
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpClient.<>c.<ConnectAsync>b__27_1(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Transport.TcpIp.Concrete.TcpIpTransport.<ReOpen>d__39.MoveNext() in D:\Git\CommunicationWebService\src\Communication.TcpIp\Concrete\TcpIpTransport.cs:line 141
2018-11-26 12:56:52.158 +07:00 [ERR] Ошибка инициализации соединения: "Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение 192.168.100.3:50000"
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (0x80004005): Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение 192.168.100.3:50000
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpClient.<>c.<ConnectAsync>b__27_1(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Transport.TcpIp.Concrete.TcpIpTransport.<ReOpen>d__39.MoveNext() in D:\Git\CommunicationWebService\src\Communication.TcpIp\Concrete\TcpIpTransport.cs:line 141
2018-11-26 12:56:56.221 +07:00 [ERR] Ошибка инициализации соединения: "Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение 192.168.100.3:50000"
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (0x80004005): Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение 192.168.100.3:50000
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpClient.<>c.<ConnectAsync>b__27_1(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Transport.TcpIp.Concrete.TcpIpTransport.<ReOpen>d__39.MoveNext() in D:\Git\CommunicationWebService\src\Communication.TcpIp\Concrete\TcpIpTransport.cs:line 141
